Tunable Shuffleboard Values
Team2068/Muhkeighnzeigh pull request #8
Opened 2023-01-08 20:15 UTC by schineaj23

Opening this on behalf of @AllusionistZ

2023-01-08 20:20 UTC, schineaj23 commented on src/main/java/frc/robot/commands/DebugValue.java
> +    public static java.lang.Object Get(String DataName) {
Our method and variable names follow the Java/Google style guide, camelCase with first word lowercased.

2023-01-08 20:20 UTC, schineaj23 commented on src/main/java/frc/robot/subsystems/ExampleSubsystem.java
> +    String DataName = "TestValue";
Tests should be in a test directory instead of placeholder commands

2023-01-08 20:20 UTC, schineaj23 commented on src/main/java/frc/robot/commands/DebugValue.java
> +    public static java.lang.Object Get(String DataName) {
Small style nitpick: Perhaps import `java.lang.Object` instead of directly referencing it.

2023-01-09 01:54 UTC, Ayidana-Aboraah commented on src/main/java/frc/robot/commands/DebugValue.java
> +    public static void Set(String DataName, double Data) {
Might want  to make Data generic.

2023-01-09 01:56 UTC, RestoneAGX commented on src/main/java/frc/robot/commands/DebugValue.java
> +        NetworkTable Table = NetworkTableInstance.getDefault().getTable(DataName);
Table could be scoped to the class to reduce the repetition. (Yeah, this is a hardcore annoying for literally 19).

2023-01-09 01:57 UTC, RestoneAGX requested changes
Just commit 1 more refactor with the changes specified, and you'll pass. ;]

2023-01-09 21:08 UTC, AllusionistZ commented on src/main/java/frc/robot/commands/DebugValue.java
> +    public static void Set(String DataName, double Data) {
Could data be set as an object type instead which would accept all values? If not, I can figure out a way to make it a generic.
(nevermind, ignore)

2023-01-09 23:06 UTC, merged